CREATE TABLE `data_platform_orders_item_data`
(
    `OrderID`                                int(16) NOT NULL,
    `OrderItem`                              int(6) NOT NULL,
    `OrderItemCategory`                      varchar(4) NOT NULL,
    `OrderItemText`                          varchar(100) NOT NULL,
    `Product`                                varchar(40) NOT NULL,
    `ProductStandardID`                      varchar(18) NOT NULL,
    `PricingDate`                            date NOT NULL,
    `OrderQuantity`                          float(15) NOT NULL,
    `OrderQuantityUnit`                      varchar(3) NOT NULL,
    `StockConfirmationPartnerFunction`       varchar(40) DEFAULT NULL,
    `StockConfirmationBusinessPartner`       int(12) DEFAULT NULL,
    `StockConfirmationPlant`                 varchar(4) DEFAULT NULL,
    `StockConfirmationPolicy`                varchar(4) DEFAULT NULL,
    `StockConfirmationStatus`                varchar(2) DEFAULT NULL,
    `ConfdDelivQtyInOrderQtyUnit`            float(15) DEFAULT NULL,
    `ItemGrossWeight`                        float(15) DEFAULT NULL,
    `ItemNetWeight`                          float(15) DEFAULT NULL,
    `ItemWeightUnit`                         varchar(3) DEFAULT NULL,
    `NetAmount`                              float(13) DEFAULT NULL,
    `TaxAmount`                              float(13) DEFAULT NULL,
    `GrossAmount`                            float(13) DEFAULT NULL,
    `ProductGroup`                           varchar(9) DEFAULT NULL,
    `BillingDocumentDate`                    date DEFAULT NULL,
    `ProductionPlantBusinessPartner`         int(12) DEFAULT NULL,
    `ProductionPlant`                        varchar(4) DEFAULT NULL,
    `ProductionPlantTimeZone`                varchar(3) DEFAULT NULL,
    `ProductionPlantStorageLocation`         varchar(4) DEFAULT NULL,
    `IssuingPlantBusinessPartner`            int(12) DEFAULT NULL,
    `IssuingPlant`                           varchar(4) DEFAULT NULL,
    `IssuingPlantTimeZone`                   varchar(3) DEFAULT NULL,
    `IssuingPlantStorageLocation`            varchar(4) DEFAULT NULL,
    `ReceivingPlantBusinessPartner`          int(12) DEFAULT NULL,
    `ReceivingPlant`                         varchar(4) DEFAULT NULL,
    `ReceivingPlantTimeZone`                 varchar(3) DEFAULT NULL,
    `ReceivingPlantStorageLocation`          varchar(4) DEFAULT NULL,
    `ProductIsBatchManagedInProductionPlant` tinyint(1) DEFAULT NULL,
    `ProductIsBatchManagedInIssuingPlant`    tinyint(1) DEFAULT NULL,
    `ProductIsBatchManagedInReceivingPlant`  tinyint(1) DEFAULT NULL,
    `ProductionPlantBatch`                   varchar(10) DEFAULT NULL,
    `IssuingPlantBatch`                      varchar(10) DEFAULT NULL,
    `ReceivingPlantBatch`                    varchar(10) DEFAULT NULL,
    `ProductionPlantBatchValidityStartDate`  date DEFAULT NULL,
    `ProductionPlantBatchValidityEndDate`    date DEFAULT NULL,
    `IssuingPlantBatchValidityStartDate`     date DEFAULT NULL,
    `IssuingPlantBatchValidityEndDate`       date DEFAULT NULL,
    `ReceivingPlantBatchValidityStartDate`   date DEFAULT NULL,
    `ReceivingPlantBatchValidityEndDate`     date DEFAULT NULL,
    `Incoterms`                              varchar(4) DEFAULT NULL,
    `BPTaxClassification`                    varchar(1) NOT NULL,
    `ProductTaxClassification`               varchar(1) NOT NULL,
    `BPAccountAssignmentGroup`               varchar(2) NOT NULL,
    `ProductAccountAssignmentGroup`          varchar(2) NOT NULL,
    `PaymentTerms`                           varchar(4) NOT NULL,
    `PaymentMethod`                          varchar(1) NOT NULL,
    `DocumentRjcnReason`                     tinyint(1) DEFAULT NULL,
    `ItemBillingBlockReason`                 tinyint(1) DEFAULT NULL,
    `Project`                                varchar(24) DEFAULT NULL,
    `AccountingExchangeRate`                 float(8) DEFAULT NULL,
    `ReferenceDocument`                      int(12) DEFAULT NULL,
    `ReferenceDocumentItem`                  int(6) DEFAULT NULL,
    `ItemDeliveryStatus`                     varchar(2) DEFAULT NULL,
    `IssuingStatus`                          varchar(2) DEFAULT NULL,
    `ReceivingStatus`                        varchar(2) DEFAULT NULL,
    `BillingStatus`                          varchar(2) DEFAULT NULL,
    `TaxCode`                                varchar(2) DEFAULT NULL,
    `TaxRate`                                varchar(6) DEFAULT NULL,
    `CountryOfOrigin`                        varchar(3) DEFAULT NULL,

    PRIMARY KEY (`OrderID`, `OrderItem`, `Product`),
    
    CONSTRAINT `DataPlatformOrdersItemData_fk` FOREIGN KEY (`OrderID`) REFERENCES `data_platform_orders_header_data` (`OrderID`),
    CONSTRAINT `DataPlatformOrdersItemDataProduct_fk` FOREIGN KEY (`Product`) REFERENCES `data_platform_product_master_general_data` (`Product`),
    CONSTRAINT `DataPlatformOrdersItemDataProductGroup_fk` FOREIGN KEY (`ProductGroup`) REFERENCES `data_platform_product_group_product_group_data` (`ProductGroup`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
